kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: hostnic
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - nodes/status
    verbs:
      - patch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: hostnic
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: hostnic
subjects:
- kind: ServiceAccount
  name: hostnic
  namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hostnic
  namespace: kube-system
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: kube-hostnic-cni-cfg
  namespace: kube-system
  labels:
    tier: node
    app: hostnic
data:
  10-hostnic.conf: |
    {
        "cniVersion": "0.3.1",
        "name": "hostnic",
        "type": "hostnic",
        "bindaddr":"localhost:31080",
        "ipam":{
          "routes":[{"dst":"10.96.0.0/24","gw":"0.0.0.0"}]
        },
        "isGateway": true
    }
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: kube-qingcloud-hostnic
  namespace: kube-system
  labels:
    tier: node
    app: kube-qingcloud-hostnic
spec:
  template:
    metadata:
      labels:
        tier: node
        app: kube-qingcloud-hostnic
    spec:
      hostNetwork: true
      nodeSelector:
        beta.kubernetes.io/arch: amd64
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      serviceAccountName: hostnic
      containers:
      - name: kube-qingcloud-hostnic
        image: dockerhub.qingcloud.com/qingcloud/hostnic-cni:hostnic-cni-v0.8-1-g89dae0f
        command: [ "start" ]
        securityContext:
          privileged: true
        env:
        - name: LOGLEVEL
          value: "info"

        - name: VXNETS
          value: "vxnet-2xj9lrp,vxnet-h00g66q"

        - name: POOLSIZE
          value: "3"

        volumeMounts:
        - name: hostnic-cfg
          mountPath: /etc/cni/

        - name: qingcloud-cfg
          mountPath: /etc/qingcloud/

      volumes:
      - name: hostnic-cfg
        configMap:
          name: kube-hostnic-cni-cfg

      - name: qingcloud-cfg
        hostPath:
          path: /etc/qingcloud/
